Repository codeit-part4-6/GlobalNomad, pull requests merged in 2025-01, with the labels that each got.

#7 [feat] 공통 컬러팔레트, 폰트 세팅
  app/layout.tsx
  app/test/page.tsx
  package-lock.json
  styles/globals.css
  tailwind.config.ts
Labels: 공통

#12 [feat] 공통 모달
  app/test/page.tsx
  components/common/modal/modal.tsx
  components/common/modal/overlay-container.tsx
  components/common/modal/review-modal.tsx
  public/icon/icon_confirm.svg
  styles/globals.css
  tailwind.config.ts
Labels: 공통

#17 navbar-guest 버전
  app/test/page.tsx
  components/common/navbar/Navbar.tsx
  public/icon/ic_notification.svg
  public/img/img_navlogo.svg
Labels: 공통

#19 INPUT 박스 공통컴포넌트
  app/components/InputPage.tsx
  app/components/page.tsx
  app/main/page.tsx
  components/common/Input.tsx
  package-lock.json
  package.json
Labels: 공통

#25 input 박스 아이콘영역 추가
  app/components/InputPage.tsx
  components/common/Input.tsx
  public/icon/ic_eyes_off.svg
  public/icon/ic_eyes_on.svg
Labels: 공통

#33 회원가입 페이지 layout
  app/signin/page.tsx
  app/signup/page.tsx
Labels: html&css

#42 메인페이지 레이아웃
  app/components/mypage.tsx
  app/signin/.gitkeep
  app/signin/page.tsx
  app/signup/.gitkeep
  app/signup/page.tsx
Labels: html&css

#36 회원가입 layout -> develop
  app/signin/.gitkeep
  app/signin/page.tsx
  app/signup/.gitkeep
  app/signup/page.tsx
Labels: html&css

#41 [feat] : kakaomap 작업 완료
  app/components/kakomap.tsx
  app/components/layout.tsx
  app/components/page.tsx
  app/layout.tsx
  app/signin/page.tsx
  next.config.ts
  package.json
  public/icon/icon_location.svg
  tailwind.config.ts
  tsconfig.json
Labels: 기능개발

#37 [feat] 공통 사이드 네비게이션 메뉴
  app/mypage/layout.tsx
  app/mypage/page.tsx
  components/common/modal/overlay-container.tsx
  components/common/side-navigation/side-navi.tsx
  components/common/side-navigation/test.tsx
  public/icon/icon_accoutn_check.svg
  public/icon/icon_accoutn_uncheck.svg
  public/icon/icon_calendar_check.svg
  public/icon/icon_calendar_uncheck.svg
  public/icon/icon_cog.svg
  public/icon/icon_cog_un.svg
  public/icon/icon_profile-button.svg
  public/icon/icon_textbox_check.svg
  public/icon/icon_textbox_uncheck.svg
  public/img/img_default_profile.svg
  tailwind.config.ts
Labels: 공통

#38 [feat] : pagenation 작업 완료
  app/components/page.tsx
  app/components/pagenation.tsx
  components/common/pagenation.tsx
  public/icon/icon_next.svg
  public/icon/icon_prevate.svg
Labels: 공통

#43 마이페이지 레이아웃
  app/components/mypage.tsx
  app/components/page.tsx
Labels: html&css

#47 [chore] footer,header 루트 layout 추가
  app/components/page.tsx
  app/layout.tsx
  app/mypage/layout.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  components/common/footer.tsx
  components/common/navbar.tsx
  components/common/navbar/navbar.tsx
Labels: html&css

#50 회원가입 페이지 기능
  app/ClientSideLayout.tsx
  app/components/kakomap.tsx
  app/components/layout.tsx
  app/components/mypage.tsx
  app/components/page.tsx
  app/components/pagenation.tsx
  app/layout.tsx
  app/mypage/layout.tsx
  app/mypage/page.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  components/common/footer.tsx
  components/common/modal/overlay-container.tsx
  components/common/navbar.tsx
  components/common/navbar/navbar.tsx
  components/common/pagenation.tsx
  components/common/side-navigation/side-navi.tsx
  components/common/side-navigation/test.tsx
  next.config.ts
  package-lock.json
  package.json
  public/icon/ic_facebook.svg
  public/icon/ic_instagram.svg
  public/icon/ic_twitter.svg
  public/icon/ic_youtube.svg
  public/icon/icon_accoutn_check.svg
  public/icon/icon_accoutn_uncheck.svg
  public/icon/icon_calendar_check.svg
  public/icon/icon_calendar_uncheck.svg
  public/icon/icon_cog.svg
  public/icon/icon_cog_un.svg
  public/icon/icon_location.svg
  public/icon/icon_next.svg
  public/icon/icon_prevate.svg
  public/icon/icon_profile-button.svg
  public/icon/icon_textbox_check.svg
  public/icon/icon_textbox_uncheck.svg
  public/img/img_default_profile.svg
  service/api.tsx
  service/api/instance.tsx
  service/api/users/users.api.ts
  service/api/users/users.types.ts
  service/store/store.tsx
  tailwind.config.ts
  tsconfig.json
Labels: 기능개발

#56 회원가입 기능(최종수정)
  app/signup/page.tsx
  service/api/users/postSignup.api.ts
  types/postSignup.types.ts
Labels: 기능개발

#55 [feat] 예약 내역 레이아웃
  app/ClientSideLayout.tsx
  app/components/kakomap.tsx
  app/components/layout.tsx
  app/components/mypage.tsx
  app/components/page.tsx
  app/components/pagenation.tsx
  app/components/reservation-list.tsx
  app/layout.tsx
  app/mypage/layout.tsx
  app/mypage/page.tsx
  app/signin/.gitkeep
  app/signin/page.tsx
  app/signup/.gitkeep
  app/signup/page.tsx
  components/common/footer.tsx
  components/common/modal/modal.tsx
  components/common/modal/overlay-container.tsx
  components/common/modal/review-modal.tsx
  components/common/navbar.tsx
  components/common/navbar/navbar.tsx
  components/common/pagenation.tsx
  components/common/reservation-list/custom-select.tsx
  components/common/side-navigation/side-navi.tsx
  components/common/side-navigation/test.tsx
  constant/reservation-list-constant.ts
  next.config.ts
  package-lock.json
  package.json
  public/icon/ic_close_button.svg
  public/icon/ic_facebook.svg
  public/icon/ic_instagram.svg
  public/icon/ic_star.svg
  public/icon/ic_twitter.svg
  public/icon/ic_unstar.svg
  public/icon/ic_youtube.svg
  public/icon/icon_accoutn_check.svg
  public/icon/icon_accoutn_uncheck.svg
  public/icon/icon_arrow_down.svg
  public/icon/icon_calendar_check.svg
  public/icon/icon_calendar_uncheck.svg
  public/icon/icon_cog.svg
  public/icon/icon_cog_un.svg
  public/icon/icon_location.svg
  public/icon/icon_next.svg
  public/icon/icon_prevate.svg
  public/icon/icon_profile-button.svg
  public/icon/icon_textbox_check.svg
  public/icon/icon_textbox_uncheck.svg
  public/img/img_default_profile.svg
  public/img/img_non_data.svg
  service/api.tsx
  service/api/instance.tsx
  service/api/users/users.api.ts
  service/api/users/users.types.ts
  service/store/store.tsx
  styles/globals.css
  tailwind.config.ts
  tsconfig.json
  types/review-modal-props.ts
Labels: html&css

#60 마이페이지 레이아웃
  app/components/page.tsx
  app/components/reservation-list.tsx
  app/mypage/page.tsx
  components/common/modal/modal.tsx
  components/common/modal/review-modal.tsx
  components/common/reservation-list/custom-select.tsx
  components/common/side-navigation/mypage.tsx
  components/common/side-navigation/side-navi.tsx
  constant/reservation-list-constant.ts
  public/icon/ic_close_button.svg
  public/icon/ic_star.svg
  public/icon/ic_unstar.svg
  public/icon/icon_arrow_down.svg
  public/img/img_non_data.svg
  styles/globals.css
  tailwind.config.ts
  types/review-modal-props.ts
Labels: html&css, 대표작업

#57 [feat] 예약 내역 레이아웃(develop 으로 병합)
  components/common/modal/review-modal.tsx
Labels: html&css

#54 [feat] 체험관리 레이아웃
  app/myactivities/activities-card.tsx
  app/myactivities/activities-modify.tsx
  app/myactivities/activities-register.tsx
  app/myactivities/myactivities.tsx
  app/myactivities/page.tsx
  package-lock.json
  package.json
  public/icon/ic_meatball.svg
  public/icon/ic_star.svg
  public/img/img_activities_test.png
  public/img/img_empty.png
  styles/globals.css
Labels: html&css

#65 [feat] 내 체험관리 레이아웃 (develop 으로 병합)
  app/myactivities/activities-card.tsx
  app/myactivities/activities-modify.tsx
  app/myactivities/activities-register.tsx
  app/myactivities/myactivities.tsx
  app/myactivities/page.tsx
  package-lock.json
  public/icon/ic_meatball.svg
  public/img/img_activities_test.png
  public/img/img_empty.png
Labels: Dev반영

#66 [feat] 예약 현황 레이아웃
  app/ClientSideLayout.tsx
  app/components/page.tsx
  app/components/reservation-calendar.tsx
  app/components/reservation-list.tsx
  app/layout.tsx
  app/myactivities/activities-card.tsx
  app/myactivities/activities-modify.tsx
  app/myactivities/activities-register.tsx
  app/myactivities/myactivities.tsx
  app/myactivities/page.tsx
  app/mypage/layout.tsx
  app/mypage/page.tsx
  components/common/modal/modal.tsx
  components/common/modal/review-modal.tsx
  components/common/side-navigation/test.tsx
  components/reservation-calendar/big-calendar.tsx
  components/reservation-calendar/calendar-header.tsx
  components/reservation-list/custom-select.tsx
  components/side-navigation/mypage.tsx
  components/side-navigation/side-navi.tsx
  constant/reservation-list-constant.ts
  package-lock.json
  package.json
  public/icon/ic_chevron_down.svg
  public/icon/ic_close_button.svg
  public/icon/ic_meatball.svg
  public/icon/ic_star.svg
  public/icon/ic_unstar.svg
  public/icon/icon_arrow_down.svg
  public/img/img_activities_test.png
  public/img/img_empty.png
  public/img/img_non_data.svg
  styles/globals.css
  tailwind.config.ts
  types/review-modal-props.ts
Labels: html&css

#71 [style] : 체험 상세 페이지 작업
  app/activities/banner.tsx
  app/activities/kakomap.tsx
  app/activities/layout.tsx
  app/activities/page.tsx
  app/activities/reservation.tsx
  app/activities/reviews.tsx
  components/common/pagenation.tsx
  next.config.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: html&css

#70 [feat] 내체험등록 중간영역 ui
  app/activities/banner.tsx
  app/activities/kakomap.tsx
  app/activities/layout.tsx
  app/activities/page.tsx
  app/activities/reservation.tsx
  app/activities/reviews.tsx
  app/myactivities/activities-register.tsx
  app/myactivities/address-modal.tsx
  app/myactivities/myactivities.tsx
  app/myactivities/page.tsx
  components/common/pagenation.tsx
  components/common/selectbox.tsx
  next.config.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: Dev반영

#76 [feat]: 예약 현황 페이지 레이아웃
  app/mypage/page.tsx
  components/common/modal/reservation-container.tsx
  components/common/modal/reservation-modal.tsx
  components/common/non-data.tsx
  components/reservation-calendar/big-calendar.tsx
  components/reservation-calendar/confirm-button.tsx
  components/reservation-calendar/confirm-chip.tsx
  components/reservation-calendar/reservation-calendar.tsx
  components/reservation-calendar/reservation-info.tsx
  components/reservation-list/reservation-list.tsx
  constant/reservation-list-constant.ts
  package-lock.json
  package.json
  tailwind.config.ts
  types/reservation-info-props.ts
Labels: html&css

#78 [refactor] 내체험관리 컴포넌트로 파일이동
  app/myactivities/myactivities.tsx
  app/myactivities/page.tsx
  app/mypage/page.tsx
  components/myactivities/activities-card.tsx
  components/myactivities/activities-modify.tsx
  components/myactivities/activities-register.tsx
  components/myactivities/address-modal.tsx
  components/myactivities/myactivities.tsx
  components/side-navigation/side-navi.tsx
Labels: Dev반영

#81 로그인 페이지 기능
  app/signin/page.tsx
  app/signup/page.tsx
  components/common/navbar.tsx
  package-lock.json
  package.json
  service/api/auth/postSignin.api.ts
  service/api/auth/postTokens.api.ts
  service/api/instance.tsx
  service/api/users/postSignup.api.ts
  service/store/authStore.tsx
  service/store/store.tsx
  types/postSignin.types.ts
Labels: 기능개발, 대표작업

#86 [style] : 체험 상세 페이지 작업
  .gitignore
  app/activities/banner.tsx
  app/activities/page.tsx
  app/activities/reservation.tsx
  app/activities/reviews.tsx
  components/activities/kakomap.tsx
  components/activities/reservation.tsx
  components/activities/reviews.tsx
  components/activities/sm-calendar.tsx
  components/common/pagenation.tsx
  public/icon/icon_cancle.png
  public/icon/icon_minus.png
  public/icon/icon_plus.png
Labels: html&css

#89 [페이지] 체험 상세 디자인 작업
  .gitignore
  app/activities/banner.tsx
  app/activities/page.tsx
  app/activities/reservation.tsx
  app/activities/reviews.tsx
  components/activities/kakomap.tsx
  components/activities/reservation.tsx
  components/activities/reviews.tsx
  components/activities/sm-calendar.tsx
  components/common/pagenation.tsx
  public/icon/icon_cancle.png
  public/icon/icon_minus.png
  public/icon/icon_plus.png
Labels: html&css

#88 [페이지] 예약 내역 페이지 기능 구현 / 레이아웃 수정
  app/mypage/layout.tsx
  app/mypage/page.tsx
  components/common/footer.tsx
  components/common/modal/modal.tsx
  components/common/modal/review-modal.tsx
  components/common/non-data.tsx
  components/myactivities/activities-card.tsx
  components/myactivities/myactivities.tsx
  components/reservation-list/custom-select.tsx
  components/reservation-list/reservation-list.tsx
  components/reservation-list/star-rating.tsx
  components/side-navigation/side-navi.tsx
  package-lock.json
  package.json
  public/icon/ic_sortIcon.svg
  service/api/reservation-list/getAccessToken.ts
  service/api/reservation-list/getReservation.api.ts
  service/api/reservation-list/patchReservation.api.ts
  service/api/reservation-list/postReview.api.ts
  service/lib/formatted-dot-date.ts
  styles/globals.css
  tailwind.config.ts
  types/reservation-list.ts
  types/server-error.types.ts
Labels: html&css, 기능개발

#92 [style] footer, 내체험관리 잔여수정
  app/ClientSideLayout.tsx
  app/components/page.tsx
  components/common/dropbox.tsx
  components/common/footer.tsx
  components/common/selectbox.tsx
  components/myactivities/activities-card.tsx
  components/myactivities/activities-register.tsx
Labels: Dev반영

#98 [style] 검색 컴포넌트 추가
  app/page.tsx
  components/main/entire-card.tsx
  components/main/option.tsx
  components/main/popular-card.tsx
  components/main/search-list.tsx
  components/main/search.tsx
  package-lock.json
  package.json
  styles/globals.css
Labels: html&css

#99 navbar 배경색상 추가
  app/signin/page.tsx
  app/signup/page.tsx
  components/common/navbar.tsx
Labels: html&css

#100 [style] swiper ui 수정
  app/page.tsx
  components/main/entire-card.tsx
  components/main/option.tsx
  components/main/popular-card.tsx
  components/main/search-list.tsx
  public/icon/ic_arrow_next.svg
  styles/globals.css
Labels: html&css

#101 [feat] 무한스크롤 컴포넌트
  app/components/InfinitePage.tsx
  app/components/page.tsx
  components/common/lnfiniteScroll.tsx
  package-lock.json
  package.json
  styles/globals.css
Labels: 공통

#102 [feat] 내체험관리 내역조회 기능 추가
  components/common/lnfiniteScroll.tsx
  components/myactivities/activities-card.tsx
  components/myactivities/myactivities.tsx
  service/api/myactivities/getActivities.ts
  types/myactivities.ts
Labels: Dev반영

#103 [refactor] : 체험 상세 디자인 수정 및 스켈레톤 적용
  app/activities/layout.tsx
  app/activities/page.tsx
  components/activities/reservation.tsx
  components/activities/reviews.tsx
  components/activities/side-reservation.tsx
  components/common/skeleton.tsx
  utiles/format-date.tsx
  utiles/initial-device.tsx
Labels: html&css
