Repository codeit-part4-6/GlobalNomad, pull requests merged in 2025-02, with the labels that each got.

#106 마이페이지 기능
  app/signin/page.tsx
  app/signup/page.tsx
  components/common/navbar.tsx
  components/side-navigation/mypage.tsx
  service/api/users/patchMypage.api.ts
  service/api/users/postSignup.api.ts
  service/store/authStore.tsx
  types/patchMypage.types.ts
Labels: 기능개발, 대표작업

#108 [feat] 체험등록 기능추가
  components/common/Input.tsx
  components/common/selectbox.tsx
  components/myactivities/activities-register.tsx
  components/myactivities/image-list.tsx
  components/myactivities/myactivities.tsx
  components/myactivities/time-list.tsx
  service/api/myactivities/postActivities.ts
  service/api/myactivities/postImage.api.ts
  service/lib/fotmatted-hour-time.ts
  styles/globals.css
  types/postActivities.types.ts
Labels: Dev반영

#111 [style] margin 수정 1차
  app/page.tsx
  components/main/entire-card.tsx
  components/main/option.tsx
  components/main/popular-card.tsx
  components/main/search-list.tsx
  styles/globals.css
Labels: html&css

#112 [feat] : 체험 상세 API 연동[1차 작업]
  app/activities/[id]/layout.tsx
  app/activities/[id]/page.tsx
  app/activities/[id]/skeleton.tsx
  app/activities/layout.tsx
  app/activities/page.tsx
  components/activities/kakomap.tsx
  components/activities/reservation.tsx
  components/activities/reviews.tsx
  components/activities/side-reservation.tsx
  components/activities/sm-calendar.tsx
  components/common/button.tsx
  components/common/pagenation.tsx
  package.json
  service/api/activities/getActivitiesInfo.ts
  service/api/activities/postActivities.ts
  types/activities-info.ts
  utils/format-date.tsx
  utils/format-number.tsx
  utils/initial-device.tsx
Labels: 기능개발

#116 [페이지] : 내체험 수정삭제 기능
  components/myactivities/activities-card.tsx
  components/myactivities/activities-modify.tsx
  components/myactivities/activities-register.tsx
  components/myactivities/image-list.tsx
  components/myactivities/myactivities.tsx
  components/myactivities/time-list.tsx
  service/api/myactivities/deleteActivities.api.ts
  service/api/myactivities/getActivitiesId.api.ts
  service/api/myactivities/patchActivities.api.ts
  types/getActivitiesId.types.ts
  types/patchActivities.types.ts
  types/postActivities.types.ts
Labels: Dev반영

#115 [페이지] : 체험 상세 예약 기능 작업
  app/activities/[id]/page.tsx
  components/activities/side-reservation.tsx
  components/activities/sm-calendar.tsx
  service/api/activities/postActivities.ts
  types/activities-info.ts
Labels: 버그, 기능개발

#119 [페이지] 예약 현황 기능 1차
  app/mypage/page.tsx
  components/common/modal/reservation-container.tsx
  components/common/modal/reservation-modal.tsx
  components/common/modal/review-modal.tsx
  components/common/navbar.tsx
  components/common/non-data.tsx
  components/myactivities/time-list.tsx
  components/reservation-calendar/big-calendar.tsx
  components/reservation-calendar/calendar-header.tsx
  components/reservation-calendar/confirm-button.tsx
  components/reservation-calendar/reservation-calendar.tsx
  components/reservation-calendar/reservation-info.tsx
  components/reservation-list/reservation-list.tsx
  service/api/reservation-calendar/getActivities.api.ts
  service/api/reservation-calendar/getReservationDashboard.api.ts
  service/api/reservation-calendar/getReservations.api.ts
  service/api/reservation-calendar/getReservedSchedule.api.ts
  service/api/reservation-calendar/patchReservations.api.ts
  service/api/reservation-list/getReservation.api.ts
  types/activities.ts
  types/my-reservations.ts
  types/reservation-dashboard.ts
  types/reserved-schedule.ts
  utils/formatted-dot-date.ts
  utils/formatted-price.ts
  utils/fotmatted-hour-time.ts
Labels: 기능개발, Dev반영

#120 [페이지] 예약 현황 기능 대표 브랜치로 병합
  components/reservation-calendar/reservation-info.tsx
Labels: 기능개발

#121 [페이지] 예약 현황 기능 2차
  components/reservation-calendar/reservation-info.tsx
Labels: 기능개발, 대표작업

#124 [fix] : 체험 상세 버그 수정(스케쥴 validation, 후기 평점, 체험 상세 내용 표시
  app/activities/[id]/page.tsx
  components/activities/reviews.tsx
  components/activities/sm-calendar.tsx
Labels: 버그

#122 [fix] 체험 등록,수정 버그 수정
  components/myactivities/activities-modify.tsx
  components/myactivities/image-list.tsx
  components/myactivities/myactivities.tsx
  components/myactivities/time-list.tsx
  types/patchActivities.types.ts
Labels: 버그, Dev반영

#128 로그인페이지 간편로그인&회원가입
  app/oauth/kakao/page.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  package-lock.json
  package.json
  service/api/oauth/postOAuth.api.tsx
  service/api/oauth/postOAuthSignin.api.tsx
  service/api/oauth/postOAuthSignup.api.tsx
  service/store/authStore.tsx
  tailwind.config.ts
Labels: 기능개발, 대표작업

#132 [fix] 체험 등록 수정사항 반영
  components/common/lnfiniteScroll.tsx
  components/myactivities/activities-modify.tsx
  components/myactivities/image-list.tsx
  components/myactivities/myactivities.tsx
  components/myactivities/non-data.tsx
Labels: Dev반영

#134 [페이지] 사이드 네비게이션 병렬 라우트 적용
  app/mypage/@menu/default.tsx
  app/mypage/@menu/myinfo/page.tsx
  app/mypage/@menu/reserveCalendar/page.tsx
  app/mypage/@menu/reserveList/page.tsx
  app/mypage/@menu/treatReservation/page.tsx
  app/mypage/@side/default.tsx
  app/mypage/layout.tsx
  app/mypage/page.tsx
  components/common/modal/modal.tsx
  components/common/modal/reservation-modal.tsx
  components/common/modal/review-modal.tsx
  components/myactivities/activities-modify.tsx
  components/myactivities/activities-register.tsx
  components/myactivities/myactivities.tsx
  components/reservation-calendar/confirm-button.tsx
  components/reservation-calendar/reservation-calendar.tsx
  components/reservation-list/reservation-list.tsx
  components/side-navigation/mypage.tsx
  components/side-navigation/side-navi.tsx
  service/api/myactivities/getActivitiesId.api.ts
  utils/formatted-dot-date.ts
Labels: 기능개발

#136 로그인페이지 간편로그인 로그인, 회원가입 분리
  app/oauth/google/.gitkeep
  app/oauth/kakao/page.tsx
  app/oauth/kakao/signup/page.tsx
  app/signup/page.tsx
Labels: 기능개발, 대표작업

#137 [feat] 알림내역 구현
  app/signin/page.tsx
  components/common/navbar.tsx
  components/common/notification.tsx
  components/myactivities/activities-modify.tsx
  components/myactivities/activities-register.tsx
  public/icon/ic_close_black.svg
  public/icon/ic_noti_blue.svg
  public/icon/ic_noti_red.svg
  service/api/mynotifications/deleteMyNotifications.api.ts
  service/api/mynotifications/getMynotifications.api.ts
  types/getMynotifications.ts
Labels: 기능개발, Dev반영

#139 [페이지] 404 Not Found
  app/mypage/layout.tsx
  app/not-found.tsx
  public/img/img_404.svg
Labels: html&css

#144 [페이지] 사이드 네비 프로필 이미지 수정 기능
  app/ClientSideLayout.tsx
  app/mypage/page.tsx
  components/common/navbar.tsx
  components/side-navigation/mypage.tsx
  components/side-navigation/side-navi.tsx
  public/img/img_404.svg
  public/img/img_default_profile.svg
  service/api/users/postProfileImageUrl.api.ts
  service/store/authStore.tsx
  service/store/imageURLStore.tsx
Labels: 기능개발

#145 [refactor] 푸터css 수정, INPUT css 수정
  app/ClientSideLayout.tsx
  app/layout.tsx
  app/mypage/@menu/treatReservation/page.tsx
  app/mypage/layout.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  components/myactivities/activities-modify.tsx
  components/myactivities/myactivities.tsx
Labels: html&css, Dev반영

#146 [fix] 체험 상세 삭제시 리랜더링 버그 수정
  app/activities/[id]/page.tsx
  components/activities/reviews.tsx
  components/activities/side-reservation.tsx
  components/activities/sm-calendar.tsx
  components/common/modal/alert-modal.tsx
  service/api/activities/deleteActivities.ts
  service/api/activities/getActivitiesInfo.ts
  service/store/activitiesstore.tsx
  service/store/store.tsx
  types/activities-info.ts
  types/common/alert-modal.types.ts
  utils/admin-auth.ts
Labels: 버그, 기능개발

#150 QA 2차 수정
  app/oauth/kakao/page.tsx
  app/oauth/kakao/signup/page.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  components/common/navbar.tsx
  components/side-navigation/mypage.tsx
  service/api/instance.tsx
  service/store/authStore.tsx
Labels: Etc

#151 [fix] 없는 체험 상세 홈 화면으로 이동 및 공통 모달 일괄 적용
  app/activities/[id]/page.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  components/activities/side-reservation.tsx
  components/common/modal/alert-modal.tsx
  components/common/modal/modal.tsx
  components/myactivities/activities-modify.tsx
  components/myactivities/image-list.tsx
  components/myactivities/myactivities.tsx
  components/reservation-calendar/big-calendar.tsx
  components/reservation-calendar/confirm-button.tsx
  components/reservation-calendar/reservation-container.tsx
  components/reservation-calendar/reservation-modal.tsx
  components/reservation-list/reservation-list.tsx
  components/reservation-list/reservation-modal.tsx
  components/reservation-list/review-modal.tsx
  components/side-navigation/mypage.tsx
  types/common/alert-modal.types.ts
Labels: 버그, 공통

#153 [feat] 메인 페이지 기능 추가(페이지네이션, 검색, 카테고리 등)
  app/page.tsx
  components/common/pagenation.tsx
  components/main/entire-card.tsx
  components/main/entire-list.tsx
  components/main/option.tsx
  components/main/search-list.tsx
  components/main/search.tsx
  components/main/sort-select.tsx
  constant/categories.ts
  service/api/activities/getActivities.ts
  types/activities.ts
  utils/entire-page-size.ts
  utils/search-page-size.ts
Labels: 기능개발

#154 [feat] 메인 페이지 기능 추가
  app/page.tsx
  components/common/pagenation.tsx
  components/main/entire-card.tsx
  components/main/entire-list.tsx
  components/main/option.tsx
  components/main/popular-card.tsx
  components/main/search-list.tsx
  components/main/search.tsx
  components/main/sort-select.tsx
  constant/categories.ts
  package-lock.json
  package.json
  public/img/img_banner1.jpg
  service/api/activities/getActivities.ts
  types/activities.ts
  utils/entire-page-size.ts
  utils/search-page-size.ts
Labels: 기능개발

#161 [페이지] 체험 상세 성능 개선
  app/activities/[id]/page.tsx
  app/activities/[id]/skeleton.tsx
  components/activities/activities-update.tsx
  components/activities/banner.tsx
  components/activities/reviews.tsx
  components/activities/side-reservation.tsx
  components/activities/sm-calendar.tsx
  next.config.ts
  package.json
  service/store/activitiesstore.tsx
Labels: 기능개발, Setting

#157 [fix] 전역 상태 초기화 작업 추가
  app/activities/[id]/page.tsx
  components/activities/reviews.tsx
  components/activities/side-reservation.tsx
  components/activities/sm-calendar.tsx
  service/store/activitiesstore.tsx
Labels: 버그

#163 [페이지] 메인 페이지 ui 수정 및 디버깅
  app/page.tsx
  components/main/entire-card.tsx
  components/main/entire-list.tsx
  components/main/option.tsx
  components/main/popular-card.tsx
  components/main/search-list.tsx
  components/main/search.tsx
  components/main/sort-select.tsx
  public/icon/ic_left.svg
  public/icon/ic_right.svg
Labels: html&css, 기능개발

#164 [refactor]: 누락 패키지 파일 추가
  app/page.tsx
  components/main/main-banner.tsx
  components/main/option.tsx
  components/main/popular-card.tsx
  constant/banners.ts
  package-lock.json
  public/img/img_banner2.jpg
  public/img/img_banner3.jpg
  public/img/img_banner4.webp
Labels: 기능개발

#166 QA 3차
  app/oauth/kakao/page.tsx
  app/oauth/kakao/signup/page.tsx
  app/signin/page.tsx
Labels: Etc

#167 [fix] 체험 상세 리뷰 및 페이지네이션 버그 수정
  app/activities/[id]/page.tsx
  components/activities/kakomap.tsx
  components/activities/reviews.tsx
  components/activities/sm-calendar.tsx
  components/common/pagenation.tsx
  service/store/activitiesstore.tsx
  types/common/alert-modal.types.ts
Labels: 버그

#168 [refactor] 내 체험관리, 알림내역 등 리팩토링
  app/mypage/@menu/treatReservation/page.tsx
  components/common/dropbox.tsx
  components/common/lnfiniteScroll.tsx
  components/common/navbar.tsx
  components/common/notification.tsx
  components/common/selectbox.tsx
  components/myactivities/activities-card.tsx
  components/myactivities/activities-modify.tsx
  components/myactivities/activities-register.tsx
  components/myactivities/address-modal.tsx
  components/myactivities/image-list.tsx
  components/myactivities/myactivities.tsx
  components/myactivities/non-data.tsx
  components/myactivities/time-list.tsx
  components/reservation-list/reservation-list.tsx
  constant/myactivities-constant.ts
Labels: Dev반영

#172 QA 최종
  app/signin/page.tsx
  app/signup/page.tsx
  components/side-navigation/mypage.tsx
  package-lock.json
  package.json
  service/store/authStore.tsx
Labels: 대표작업, Etc

#173 [refactor] 알림 모달 적용 및 리뷰 조회 로딩바 추가
  components/activities/activities-update.tsx
  components/activities/kakomap.tsx
  components/activities/reviews.tsx
  components/common/pagenation.tsx
Labels: Etc

#170 [refact]: 예약 내역 / 현황 코드 리팩토링
  app/mypage/layout.tsx
  app/page.tsx
  components/common/non-data.tsx
  components/main/entire-card.tsx
  components/main/entire-list.tsx
  components/main/main-banner.tsx
  components/main/option.tsx
  components/main/popular-card.tsx
  components/main/search-list.tsx
  components/main/search.tsx
  components/main/sort-select.tsx
  components/reservation-calendar/activity-selector.tsx
  components/reservation-calendar/big-calendar.tsx
  components/reservation-calendar/confirm-button.tsx
  components/reservation-calendar/date-cell.tsx
  components/reservation-calendar/reservation-calendar.tsx
  components/reservation-calendar/reservation-info.tsx
  components/reservation-calendar/reservation-modal.tsx
  components/reservation-calendar/reservation-tab.tsx
  components/reservation-calendar/time-dropdown.tsx
  components/reservation-list/custom-select.tsx
  components/reservation-list/reservation-card.tsx
  components/reservation-list/reservation-list.tsx
  components/reservation-list/reservation-modal.tsx
  components/reservation-list/review-modal.tsx
  components/reservation-list/star-rating.tsx
  components/side-navigation/side-navi.tsx
  constant/banners.ts
  public/img/img_banner1.jpg
  public/img/img_banner1.webp
  public/img/img_banner2.jpg
  public/img/img_banner2.webp
  public/img/img_banner3.jpg
  public/img/img_banner3.webp
  types/reservation-list.ts
  utils/disable-scroll.ts
  utils/schedule-count.tsx
Labels: Etc

#176 [fix] webpack에 opt 적용
  next.config.ts
Labels: Setting

#178 [feat] 다크모드 기능 추가
  app/activities/[id]/page.tsx
  app/layout.tsx
  app/mypage/layout.tsx
  app/not-found.tsx
  app/signup/page.tsx
  components/activities/reviews.tsx
  components/activities/side-reservation.tsx
  components/common/footer.tsx
  components/common/modal/modal.tsx
  components/common/navbar.tsx
  components/common/pagenation.tsx
  components/common/theme-button.tsx
  components/common/theme-provider.tsx
  components/main/entire-card.tsx
  components/main/entire-list.tsx
  components/main/option.tsx
  components/main/popular-card.tsx
  components/main/search-list.tsx
  components/main/search.tsx
  components/main/sort-select.tsx
  components/myactivities/activities-card.tsx
  components/reservation-calendar/activity-selector.tsx
  components/reservation-calendar/reservation-calendar.tsx
  components/reservation-list/custom-select.tsx
  components/reservation-list/reservation-list.tsx
  components/reservation-list/reservation-modal.tsx
  components/side-navigation/mypage.tsx
  components/side-navigation/side-navi.tsx
  package-lock.json
  package.json
  styles/globals.css
  tailwind.config.ts
Labels: 기능개발

#177 [style]: 버튼 hover 적용
  app/page.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  components/activities/side-reservation.tsx
  components/common/modal/modal.tsx
  components/common/navbar.tsx
  components/main/entire-list.tsx
  components/main/option.tsx
  components/main/popular-card.tsx
  components/main/search-list.tsx
  components/main/search.tsx
  components/myactivities/myactivities.tsx
  components/myactivities/time-list.tsx
  components/reservation-calendar/confirm-button.tsx
  components/reservation-list/reservation-card.tsx
  components/reservation-list/reservation-modal.tsx
  components/reservation-list/review-modal.tsx
  components/side-navigation/mypage.tsx
  constant/categories.ts
  service/api/activities/getActivities.ts
  styles/globals.css
Labels: html&css

#181 [fix] pagenation 버그 수정
  components/common/pagenation.tsx
Labels: 버그

#182 [QA 수정] 알림내역 css, 체험수정 일정 scroll 추가
  components/common/lnfiniteScroll.tsx
  components/common/notification.tsx
  components/myactivities/myactivities.tsx
  components/myactivities/time-list.tsx
Labels: 버그, html&css, Dev반영

#184 [QA 수정] 예약 현황 / 내역 관련
  app/mypage/layout.tsx
  components/common/pagenation.tsx
  components/main/entire-list.tsx
  components/main/popular-card.tsx
  components/main/sort-select.tsx
  components/reservation-calendar/activity-selector.tsx
  components/reservation-list/reservation-card.tsx
Labels: 버그

#186 [style] 마이페이지 예약 내역, 내 체험관리 카드 배경색 통일
  components/main/option.tsx
  components/main/sort-select.tsx
  components/myactivities/activities-card.tsx
  components/reservation-list/reservation-card.tsx
Labels: html&css

#185 [QA] 체험 상세 수정
  components/activities/reviews.tsx
  components/activities/side-reservation.tsx
  components/common/pagenation.tsx
  service/store/activitiesstore.tsx
Labels: 버그

#187 QA 최종2
  app/signup/page.tsx
  service/api/instance.tsx
Labels: 버그, html&css

#189 [style] 다크모드 색상 변경
  app/mypage/layout.tsx
  components/common/footer.tsx
  components/common/navbar.tsx
  components/main/option.tsx
  components/main/search.tsx
  components/main/sort-select.tsx
  components/reservation-calendar/activity-selector.tsx
  components/reservation-calendar/reservation-calendar.tsx
  components/reservation-list/custom-select.tsx
  components/reservation-list/reservation-list.tsx
Labels: html&css

#190 [refactor] 알림수 추가 및 체험관리 수정
  components/activities/activities-update.tsx
  components/activities/kakomap.tsx
  components/activities/side-reservation.tsx
  components/common/dropbox.tsx
  components/common/lnfiniteScroll.tsx
  components/common/navbar.tsx
  components/common/notification.tsx
  components/common/selectbox.tsx
  components/myactivities/activities-modify.tsx
  components/myactivities/activities-register.tsx
  components/myactivities/myactivities.tsx
  components/myactivities/time-list.tsx
  service/api/mynotifications/getMynotifications.api.ts
  types/patchActivities.types.ts
Labels: Dev반영

#193 [refactor] 체험 상세 디자인 수정
  components/activities/reviews.tsx
  components/activities/side-reservation.tsx
Labels: html&css

#192 [refactor] console.log 제거
  components/myactivities/activities-register.tsx
  components/myactivities/image-list.tsx
  components/reservation-calendar/time-dropdown.tsx
Labels: Dev반영

#191 QA 최종3
  app/oauth/kakao/page.tsx
  app/oauth/kakao/signup/page.tsx
  app/signin/page.tsx
  service/api/auth/postSignin.api.ts
  service/api/instance.tsx
  service/api/oauth/postOAuth.api.tsx
  service/api/oauth/postOAuthSignin.api.tsx
  service/api/oauth/postOAuthSignup.api.tsx
Labels: Etc
